//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "events")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub hackathon_id: i32,
    pub name: String,
    pub slug: String,
    pub description: Option<String>,
    pub start_time: DateTime,
    pub end_time: DateTime,
    pub visible_to_role: Option<String>,
    pub event_type: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub location: Option<String>,
    pub is_visible: bool,
    pub points: Option<i32>,
    pub checkin_type: String,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::event_checkins::Entity")]
    EventCheckins,
    #[sea_orm(has_many = "super::event_organizers::Entity")]
    EventOrganizers,
    #[sea_orm(
        belongs_to = "super::hackathons::Entity",
        from = "Column::HackathonId",
        to = "super::hackathons::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Hackathons,
    #[sea_orm(has_many = "super::prize_required_events::Entity")]
    PrizeRequiredEvents,
}

impl Related<super::event_checkins::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventCheckins.def()
    }
}

impl Related<super::event_organizers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventOrganizers.def()
    }
}

impl Related<super::hackathons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hackathons.def()
    }
}

impl Related<super::prize_required_events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrizeRequiredEvents.def()
    }
}

impl Related<super::prize::Entity> for Entity {
    fn to() -> RelationDef {
        super::prize_required_events::Relation::Prize.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::prize_required_events::Relation::Events.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
