//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "feature")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub hackathon_id: i32,
    pub name: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::hackathons::Entity",
        from = "Column::HackathonId",
        to = "super::hackathons::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Hackathons,
    #[sea_orm(has_many = "super::judge_feature_assignment::Entity")]
    JudgeFeatureAssignment,
    #[sea_orm(has_many = "super::pairwise_comparison::Entity")]
    PairwiseComparison,
    #[sea_orm(has_many = "super::prize_feature_weight::Entity")]
    PrizeFeatureWeight,
    #[sea_orm(has_many = "super::project_feature_score::Entity")]
    ProjectFeatureScore,
}

impl Related<super::hackathons::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Hackathons.def()
    }
}

impl Related<super::judge_feature_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JudgeFeatureAssignment.def()
    }
}

impl Related<super::pairwise_comparison::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PairwiseComparison.def()
    }
}

impl Related<super::prize_feature_weight::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PrizeFeatureWeight.def()
    }
}

impl Related<super::project_feature_score::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectFeatureScore.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
