//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "hackathons")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    #[sea_orm(unique)]
    pub slug: String,
    #[sea_orm(column_type = "Text", nullable)]
    pub description: Option<String>,
    pub start_date: DateTime,
    pub end_date: DateTime,
    pub is_active: bool,
    pub created_at: DateTime,
    pub updated_at: DateTime,
    pub max_team_size: i32,
    pub banner_url: Option<String>,
    pub form_config: Option<Json>,
    pub background_url: Option<String>,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub submission_form: Option<Json>,
    pub app_icon_url: Option<String>,
    pub theme_color: Option<String>,
    pub background_color: Option<String>,
    pub submissions_closed: bool,
    pub judging_started: bool,
    pub judge_session_timeout_minutes: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::applications::Entity")]
    Applications,
    #[sea_orm(has_many = "super::events::Entity")]
    Events,
    #[sea_orm(has_many = "super::feature::Entity")]
    Feature,
    #[sea_orm(has_many = "super::judge_walk_type::Entity")]
    JudgeWalkType,
    #[sea_orm(has_many = "super::prize::Entity")]
    Prize,
    #[sea_orm(has_many = "super::project_visit::Entity")]
    ProjectVisit,
    #[sea_orm(has_many = "super::teams::Entity")]
    Teams,
    #[sea_orm(has_many = "super::user_hackathon_roles::Entity")]
    UserHackathonRoles,
}

impl Related<super::applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Applications.def()
    }
}

impl Related<super::events::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Events.def()
    }
}

impl Related<super::feature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feature.def()
    }
}

impl Related<super::judge_walk_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JudgeWalkType.def()
    }
}

impl Related<super::prize::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Prize.def()
    }
}

impl Related<super::project_visit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectVisit.def()
    }
}

impl Related<super::teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teams.def()
    }
}

impl Related<super::user_hackathon_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserHackathonRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
