//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "judge_prize_track")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub judge_id: i32,
    pub prize_id: i32,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::prize::Entity",
        from = "Column::PrizeId",
        to = "super::prize::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Prize,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::JudgeId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::prize::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Prize.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
