//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub mod prelude;

pub mod applications;
pub mod event_checkins;
pub mod event_organizers;
pub mod events;
pub mod feature;
pub mod hackathons;
pub mod judge_feature_assignment;
pub mod judge_prize_track;
pub mod judge_walk_type;
pub mod pairwise_comparison;
pub mod prize;
pub mod prize_feature_weight;
pub mod prize_required_events;
pub mod prize_track_entry;
pub mod project_feature_score;
pub mod project_visit;
pub mod submission;
pub mod submission_ai_summary;
pub mod team_invitations;
pub mod team_join_requests;
pub mod teams;
pub mod user_hackathon_roles;
pub mod users;
