//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "pairwise_comparison")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub judge_id: i32,
    pub feature_id: i32,
    pub submission_a_id: i32,
    pub submission_b_id: i32,
    pub winner_id: Option<i32>,
    pub created_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::feature::Entity",
        from = "Column::FeatureId",
        to = "super::feature::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Feature,
    #[sea_orm(
        belongs_to = "super::submission::Entity",
        from = "Column::SubmissionAId",
        to = "super::submission::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Submission2,
    #[sea_orm(
        belongs_to = "super::submission::Entity",
        from = "Column::SubmissionBId",
        to = "super::submission::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Submission1,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::JudgeId",
        to = "super::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::feature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feature.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
