//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

pub use super::applications::Entity as Applications;
pub use super::event_checkins::Entity as EventCheckins;
pub use super::event_organizers::Entity as EventOrganizers;
pub use super::events::Entity as Events;
pub use super::feature::Entity as Feature;
pub use super::hackathons::Entity as Hackathons;
pub use super::judge_feature_assignment::Entity as JudgeFeatureAssignment;
pub use super::judge_prize_track::Entity as JudgePrizeTrack;
pub use super::pairwise_comparison::Entity as PairwiseComparison;
pub use super::prize::Entity as Prize;
pub use super::prize_feature_weight::Entity as PrizeFeatureWeight;
pub use super::prize_required_events::Entity as PrizeRequiredEvents;
pub use super::prize_track_entry::Entity as PrizeTrackEntry;
pub use super::project_feature_score::Entity as ProjectFeatureScore;
pub use super::project_visit::Entity as ProjectVisit;
pub use super::submission::Entity as Submission;
pub use super::submission_ai_summary::Entity as SubmissionAiSummary;
pub use super::team_invitations::Entity as TeamInvitations;
pub use super::team_join_requests::Entity as TeamJoinRequests;
pub use super::teams::Entity as Teams;
pub use super::user_hackathon_roles::Entity as UserHackathonRoles;
pub use super::users::Entity as Users;
