//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "prize_feature_weight")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub prize_id: i32,
    pub feature_id: i32,
    #[sea_orm(column_type = "Float")]
    pub weight: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::feature::Entity",
        from = "Column::FeatureId",
        to = "super::feature::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Feature,
    #[sea_orm(
        belongs_to = "super::prize::Entity",
        from = "Column::PrizeId",
        to = "super::prize::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Prize,
}

impl Related<super::feature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feature.def()
    }
}

impl Related<super::prize::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Prize.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
