//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "project_feature_score")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub submission_id: i32,
    pub feature_id: i32,
    #[sea_orm(column_type = "Float", nullable)]
    pub score: Option<f32>,
    #[sea_orm(column_type = "Float", nullable)]
    pub variance: Option<f32>,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::feature::Entity",
        from = "Column::FeatureId",
        to = "super::feature::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Feature,
    #[sea_orm(
        belongs_to = "super::submission::Entity",
        from = "Column::SubmissionId",
        to = "super::submission::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Submission,
}

impl Related<super::feature::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Feature.def()
    }
}

impl Related<super::submission::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Submission.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
