//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.17

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(
    Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, utoipa :: ToSchema,
)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub oidc_sub: String,
    pub email: String,
    pub name: Option<String>,
    pub given_name: Option<String>,
    pub family_name: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub picture: Option<String>,
    pub oidc_issuer: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::applications::Entity")]
    Applications,
    #[sea_orm(has_many = "super::event_organizers::Entity")]
    EventOrganizers,
    #[sea_orm(has_many = "super::judge_feature_assignment::Entity")]
    JudgeFeatureAssignment,
    #[sea_orm(has_many = "super::judge_prize_track::Entity")]
    JudgePrizeTrack,
    #[sea_orm(has_many = "super::judge_walk_type::Entity")]
    JudgeWalkType,
    #[sea_orm(has_many = "super::pairwise_comparison::Entity")]
    PairwiseComparison,
    #[sea_orm(has_many = "super::project_visit::Entity")]
    ProjectVisit,
    #[sea_orm(has_many = "super::team_invitations::Entity")]
    TeamInvitations,
    #[sea_orm(has_many = "super::team_join_requests::Entity")]
    TeamJoinRequests,
    #[sea_orm(has_many = "super::teams::Entity")]
    Teams,
    #[sea_orm(has_many = "super::user_hackathon_roles::Entity")]
    UserHackathonRoles,
}

impl Related<super::applications::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Applications.def()
    }
}

impl Related<super::event_organizers::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::EventOrganizers.def()
    }
}

impl Related<super::judge_feature_assignment::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JudgeFeatureAssignment.def()
    }
}

impl Related<super::judge_prize_track::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JudgePrizeTrack.def()
    }
}

impl Related<super::judge_walk_type::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::JudgeWalkType.def()
    }
}

impl Related<super::pairwise_comparison::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::PairwiseComparison.def()
    }
}

impl Related<super::project_visit::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::ProjectVisit.def()
    }
}

impl Related<super::team_invitations::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamInvitations.def()
    }
}

impl Related<super::team_join_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::TeamJoinRequests.def()
    }
}

impl Related<super::teams::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Teams.def()
    }
}

impl Related<super::user_hackathon_roles::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserHackathonRoles.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
