//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14
#[cfg(feature = "server")]
use sea_orm::entity::prelude::*;
#[cfg(feature = "server")]
use serde::{Deserialize, Serialize};

#[cfg_attr(
    feature = "server",
    derive(
        Clone,
        Debug,
        PartialEq,
        DeriveEntityModel,
        Eq,
        Serialize,
        Deserialize,
        utoipa::ToSchema,
    )
)]
#[cfg(feature = "server")]
#[sea_orm(table_name = "messages")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sender_user_id: i32,
    pub message_group_id: i32,
    #[sea_orm(column_type = "Text")]
    pub title: String,
    #[sea_orm(column_type = "Text")]
    pub content: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[cfg(feature = "server")]
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "crate::entities::users::Entity",
        from = "Column::SenderUserId",
        to = "crate::entities::users::Column::Id"
    )]
    SenderUser,
    #[sea_orm(
        belongs_to = "super::message_groups::Entity",
        from = "Column::MessageGroupId",
        to = "super::message_groups::Column::Id"
    )]
    MessageGroups,
}

#[cfg(feature = "server")]
impl Related<super::message_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MessageGroups.def()
    }
}

#[cfg(feature = "server")]
impl Related<crate::entities::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::SenderUser.def()
    }
}

#[cfg(feature = "server")]
impl ActiveModelBehavior for ActiveModel {}
