//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14
#[cfg(feature = "server")]
use sea_orm::entity::prelude::*;
#[cfg(feature = "server")]
use serde::{Deserialize, Serialize};

#[cfg_attr(
    feature = "server",
    derive(
        Clone,
        Debug,
        PartialEq,
        DeriveEntityModel,
        Eq,
        Serialize,
        Deserialize,
        utoipa::ToSchema,
    )
)]
#[cfg(feature = "server")]
#[sea_orm(table_name = "message_groups")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub flag: String,
    #[sea_orm(column_type = "Integer", nullable)]
    pub recipient_id: Option<i32>,
    pub recipient_type: String,
    pub created_at: DateTime,
    pub updated_at: DateTime,
}

#[cfg(feature = "server")]
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::messages::Entity")]
    Messages,
    #[sea_orm(has_many = "super::message_group_users::Entity")]
    MessageGroupUsers,
}

#[cfg(feature = "server")]
impl Related<super::messages::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Messages.def()
    }
}

#[cfg(feature = "server")]
impl Related<super::message_group_users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MessageGroupUsers.def()
    }
}

#[cfg(feature = "server")]
impl ActiveModelBehavior for ActiveModel {}
