//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.14
#[cfg(feature = "server")]
use sea_orm::entity::prelude::*;
#[cfg(feature = "server")]
use serde::{Deserialize, Serialize};

#[cfg_attr(
    feature = "server",
    derive(
        Clone,
        Debug,
        PartialEq,
        DeriveEntityModel,
        Eq,
        Serialize,
        Deserialize,
        utoipa::ToSchema,
    )
)]
#[cfg(feature = "server")]
#[sea_orm(table_name = "message_group_users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub user_id: i32,
    #[sea_orm(primary_key)]
    pub message_group_id: i32,
}

#[cfg(feature = "server")]
#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::message_groups::Entity",
        from = "Column::MessageGroupId",
        to = "super::message_groups::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    MessageGroups,
    #[sea_orm(
        belongs_to = "crate::entities::users::Entity",
        from = "Column::UserId",
        to = "crate::entities::users::Column::Id",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Users,
}

#[cfg(feature = "server")]
impl Related<super::message_groups::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::MessageGroups.def()
    }
}

#[cfg(feature = "server")]
impl Related<crate::entities::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}

#[cfg(feature = "server")]
impl ActiveModelBehavior for ActiveModel {}
